
package view;
import controller.ControllerMenuRegistro;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.*;

public class MenuRegistro extends javax.swing.JFrame {

    /**
     * Creates new form MenuRegistro
     */
        public MenuRegistro() {
        initComponents();
        jTable1.setModel(modeloEstudiantes);
        jTable2.setModel(modeloDocentes);
        jTable3.setModel(modeloCursos);
        jTable4.setModel(modeloMatricula);
}
// --- CONFIGURACIÓN DE MODELOS DE TABLA ---
DefaultTableModel modeloEstudiantes = new DefaultTableModel(new String[]{"Código", "Nombre"}, 0);
DefaultTableModel modeloDocentes = new DefaultTableModel(new String[]{"Código", "Nombre"}, 0);
DefaultTableModel modeloCursos = new DefaultTableModel(new String[]{"Código", "Nombre", "Docente"}, 0);
DefaultTableModel modeloMatricula = new DefaultTableModel(new String[]{"Estudiante", "Curso", "Nota"}, 0);

    public MenuRegistro(String nombreUsuario) {
        initComponents();
        setResizable(false);
        setResizable(false); // Si quieres que no se redimensione
        setLocationRelativeTo(null); // 🔥 Esto lo centra en la pantalla
        
        jTable1.setModel(modeloEstudiantes);
        jTable2.setModel(modeloDocentes);
        jTable3.setModel(modeloCursos);
        jTable4.setModel(modeloMatricula);
        
                ocultarTodosLosPaneles();

        new PanelEstudiantesBD().cargarEstudiantes(modeloEstudiantes);
        new PanelDocentesBD().cargarDocentes(modeloDocentes);
        new PanelCursosBD().cargarCursos(modeloCursos);
        new PanelMatriculaBD().cargarMatriculas(modeloMatricula);

        // Llenar los combos
        llenarComboDocente();
        llenarComboEstudiante();
        llenarComboCurso();
    }
     private void ocultarTodosLosPaneles() {
        jPanelEstudiante.setVisible(false);
        jPanelDocente.setVisible(false);
        jPanelCurso.setVisible(false);
        jPanelMatricula.setVisible(false);
        jPanelEstudianteList.setVisible(false);
        jPanelDocenteList.setVisible(false);
        jPanelCursoList.setVisible(false);
        jPanelMatriculaList.setVisible(false);
    }

    private void mostrarPanel(JPanel panelMostrar) {
        ocultarTodosLosPaneles();
        panelMostrar.setVisible(true);
    }
        private void llenarComboDocente() {
        jComboBoxDocente.removeAllItems();
        for (int i = 0; i < modeloDocentes.getRowCount(); i++) {
            jComboBoxDocente.addItem(modeloDocentes.getValueAt(i, 0).toString()); // usa el código
        }
    }

    private void llenarComboEstudiante() {
        jComboBoxEstudiante.removeAllItems();
        for (int i = 0; i < modeloEstudiantes.getRowCount(); i++) {
            jComboBoxEstudiante.addItem(modeloEstudiantes.getValueAt(i, 0).toString());
        }
    }

    private void llenarComboCurso() {
        jComboBoxCurso.removeAllItems();
        for (int i = 0; i < modeloCursos.getRowCount(); i++) {
            jComboBoxCurso.addItem(modeloCursos.getValueAt(i, 0).toString());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelContenedor = new javax.swing.JPanel();
        jPanelEstudiante = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCodEstudiante = new javax.swing.JTextField();
        txtNomEstudiante = new javax.swing.JTextField();
        btEstudiante = new javax.swing.JButton();
        jPanelDocente = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCodDocente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNomDocente = new javax.swing.JTextField();
        btDocente = new javax.swing.JButton();
        jPanelCurso = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCodCurso = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtNomCurso = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jComboBoxDocente = new javax.swing.JComboBox<>();
        btCurso = new javax.swing.JButton();
        jPanelMatricula = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jComboBoxCurso = new javax.swing.JComboBox<>();
        btMatricula = new javax.swing.JButton();
        jComboBoxEstudiante = new javax.swing.JComboBox<>();
        txtNota = new javax.swing.JTextField();
        jPanelDocenteList = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanelEstudianteList = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelCursoList = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanelMatriculaList = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFormulario = new javax.swing.JMenu();
        jMenuEstudianteForm = new javax.swing.JMenuItem();
        jMenuDocenteForm = new javax.swing.JMenuItem();
        jMenuCursoForm = new javax.swing.JMenuItem();
        jMenuMatriculaForm = new javax.swing.JMenuItem();
        jMenuListado = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPanelContenedor.setBackground(new java.awt.Color(255, 255, 255));
        JPanelContenedor.setLayout(new java.awt.CardLayout());

        jPanelEstudiante.setBackground(new java.awt.Color(255, 255, 255));
        jPanelEstudiante.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("FORMULARIO ESTUDIANTES");
        jPanelEstudiante.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 190, 20));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Nombre:");
        jPanelEstudiante.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 60, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Codigo:");
        jPanelEstudiante.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 50, -1));
        jPanelEstudiante.add(txtCodEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 390, -1));
        jPanelEstudiante.add(txtNomEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 390, -1));

        btEstudiante.setText("AGREGAR");
        btEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEstudianteActionPerformed(evt);
            }
        });
        jPanelEstudiante.add(btEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 100, -1));

        JPanelContenedor.add(jPanelEstudiante, "card2");

        jPanelDocente.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDocente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("FORMULARIO DOCENTES");
        jPanelDocente.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 190, 20));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Nombre:");
        jPanelDocente.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 60, -1));
        jPanelDocente.add(txtCodDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 390, -1));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Codigo:");
        jPanelDocente.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 50, -1));
        jPanelDocente.add(txtNomDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 390, -1));

        btDocente.setText("AGREGAR");
        btDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDocenteActionPerformed(evt);
            }
        });
        jPanelDocente.add(btDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, 110, -1));

        JPanelContenedor.add(jPanelDocente, "card3");

        jPanelCurso.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCurso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("FORMULARIO PARA CURSOS");
        jPanelCurso.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 190, 20));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Codigo Curso:");
        jPanelCurso.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 90, -1));
        jPanelCurso.add(txtCodCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 390, -1));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Docente:");
        jPanelCurso.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 60, -1));
        jPanelCurso.add(txtNomCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 390, -1));

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Nombre Curso:");
        jPanelCurso.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 100, -1));

        jComboBoxDocente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        jPanelCurso.add(jComboBoxDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 390, -1));

        btCurso.setText("AGREGAR");
        btCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCursoActionPerformed(evt);
            }
        });
        jPanelCurso.add(btCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 110, -1));

        JPanelContenedor.add(jPanelCurso, "card4");

        jPanelMatricula.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMatricula.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("FORMULARIO PARA MATRICULAS");
        jPanelMatricula.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 220, 20));

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Nombre:");
        jPanelMatricula.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 70, -1));

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Curso:");
        jPanelMatricula.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 40, -1));

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Nota:");
        jPanelMatricula.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, -1));

        jComboBoxCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        jPanelMatricula.add(jComboBoxCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 390, -1));

        btMatricula.setText("AGREGAR");
        btMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMatriculaActionPerformed(evt);
            }
        });
        jPanelMatricula.add(btMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 110, -1));

        jComboBoxEstudiante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        jPanelMatricula.add(jComboBoxEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 390, -1));
        jPanelMatricula.add(txtNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 390, -1));

        JPanelContenedor.add(jPanelMatricula, "card5");

        jPanelDocenteList.setBackground(new java.awt.Color(255, 255, 255));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Docente", "Nombre Docente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout jPanelDocenteListLayout = new javax.swing.GroupLayout(jPanelDocenteList);
        jPanelDocenteList.setLayout(jPanelDocenteListLayout);
        jPanelDocenteListLayout.setHorizontalGroup(
            jPanelDocenteListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1001, Short.MAX_VALUE)
        );
        jPanelDocenteListLayout.setVerticalGroup(
            jPanelDocenteListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDocenteListLayout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        JPanelContenedor.add(jPanelDocenteList, "card3");

        jPanelEstudianteList.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Estudiante", "Nombre Estudiante"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanelEstudianteListLayout = new javax.swing.GroupLayout(jPanelEstudianteList);
        jPanelEstudianteList.setLayout(jPanelEstudianteListLayout);
        jPanelEstudianteListLayout.setHorizontalGroup(
            jPanelEstudianteListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEstudianteListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 989, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelEstudianteListLayout.setVerticalGroup(
            jPanelEstudianteListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEstudianteListLayout.createSequentialGroup()
                .addGap(0, 132, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JPanelContenedor.add(jPanelEstudianteList, "card2");

        jPanelCursoList.setBackground(new java.awt.Color(255, 255, 255));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Curso", "Nombre Curso", "Nombre Docente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout jPanelCursoListLayout = new javax.swing.GroupLayout(jPanelCursoList);
        jPanelCursoList.setLayout(jPanelCursoListLayout);
        jPanelCursoListLayout.setHorizontalGroup(
            jPanelCursoListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1001, Short.MAX_VALUE)
        );
        jPanelCursoListLayout.setVerticalGroup(
            jPanelCursoListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCursoListLayout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        JPanelContenedor.add(jPanelCursoList, "card4");

        jPanelMatriculaList.setBackground(new java.awt.Color(255, 255, 255));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Estudiante", "Codigo Curso", "Nota"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable4);

        javax.swing.GroupLayout jPanelMatriculaListLayout = new javax.swing.GroupLayout(jPanelMatriculaList);
        jPanelMatriculaList.setLayout(jPanelMatriculaListLayout);
        jPanelMatriculaListLayout.setHorizontalGroup(
            jPanelMatriculaListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1001, Short.MAX_VALUE)
        );
        jPanelMatriculaListLayout.setVerticalGroup(
            jPanelMatriculaListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMatriculaListLayout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        JPanelContenedor.add(jPanelMatriculaList, "card5");

        jMenuFormulario.setText("Formularios");
        jMenuFormulario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFormularioActionPerformed(evt);
            }
        });

        jMenuEstudianteForm.setText("Estudiantes");
        jMenuEstudianteForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEstudianteFormActionPerformed(evt);
            }
        });
        jMenuFormulario.add(jMenuEstudianteForm);

        jMenuDocenteForm.setText("Docentes");
        jMenuDocenteForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDocenteFormActionPerformed(evt);
            }
        });
        jMenuFormulario.add(jMenuDocenteForm);

        jMenuCursoForm.setText("Cursos");
        jMenuCursoForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCursoFormActionPerformed(evt);
            }
        });
        jMenuFormulario.add(jMenuCursoForm);

        jMenuMatriculaForm.setText("Matrícula");
        jMenuMatriculaForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMatriculaFormActionPerformed(evt);
            }
        });
        jMenuFormulario.add(jMenuMatriculaForm);

        jMenuBar1.add(jMenuFormulario);

        jMenuListado.setText("Listados");

        jMenuItem5.setText("Listados Estudiantes");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenuListado.add(jMenuItem5);

        jMenuItem6.setText("Listados Docentes");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenuListado.add(jMenuItem6);

        jMenuItem7.setText("Listados Cursos");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenuListado.add(jMenuItem7);

        jMenuItem8.setText("Listados Matriculas");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenuListado.add(jMenuItem8);

        jMenuBar1.add(jMenuListado);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuFormularioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFormularioActionPerformed
        // TODO add your handling code here
        
    }//GEN-LAST:event_jMenuFormularioActionPerformed

    private void jMenuEstudianteFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEstudianteFormActionPerformed
        // TODO add your handling code here:
        mostrarPanel(jPanelEstudiante);

    }//GEN-LAST:event_jMenuEstudianteFormActionPerformed

    private void jMenuDocenteFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDocenteFormActionPerformed
        // TODO add your handling code here:
        mostrarPanel(jPanelDocente);
    }//GEN-LAST:event_jMenuDocenteFormActionPerformed

    private void jMenuCursoFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCursoFormActionPerformed
        // TODO add your handling code here:
        mostrarPanel(jPanelCurso);
    }//GEN-LAST:event_jMenuCursoFormActionPerformed

    private void jMenuMatriculaFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMatriculaFormActionPerformed
        // TODO add your handling code here:
        mostrarPanel(jPanelMatricula);
    }//GEN-LAST:event_jMenuMatriculaFormActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
         mostrarPanel(jPanelDocenteList);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
         mostrarPanel(jPanelEstudianteList);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        mostrarPanel(jPanelCursoList);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        mostrarPanel(jPanelMatriculaList);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void btEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEstudianteActionPerformed
        // TODO add your handling code here:
        String codigo = txtCodEstudiante.getText();
        String nombre = txtNomEstudiante.getText();

        if (codigo.isEmpty() || nombre.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Completa todos los campos del estudiante.");
            return;
        }

        modeloEstudiantes.addRow(new Object[]{codigo, nombre});
        new PanelEstudiantesBD().insertarEstudiante(codigo, nombre);
        llenarComboEstudiante(); // actualizar combo
        txtCodEstudiante.setText("");
        txtNomEstudiante.setText("");
    
    }//GEN-LAST:event_btEstudianteActionPerformed

    private void btDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDocenteActionPerformed
        // TODO add your handling code here:
        String codigo = txtCodDocente.getText();
        String nombre = txtNomDocente.getText();

        if (codigo.isEmpty() || nombre.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Completa todos los campos del docente.");
            return;
        }

        modeloDocentes.addRow(new Object[]{codigo, nombre});
        new PanelDocentesBD().insertarDocente(codigo, nombre);
        llenarComboDocente(); // actualizar combo
        txtCodDocente.setText("");
        txtNomDocente.setText("");
        
    }//GEN-LAST:event_btDocenteActionPerformed

    private void btCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCursoActionPerformed
        // TODO add your handling code here:
        String codigo = txtCodCurso.getText();
        String nombre = txtNomCurso.getText();
        String docente = (String) jComboBoxDocente.getSelectedItem();

        if (codigo.isEmpty() || nombre.isEmpty() || docente == null || docente.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Completa todos los campos del curso.");
            return;
        }

        modeloCursos.addRow(new Object[]{codigo, nombre, docente});
        new PanelCursosBD().insertarCurso(codigo, nombre, docente);
        llenarComboCurso(); // actualizar combo
        txtCodCurso.setText("");
        txtNomCurso.setText("");
    }//GEN-LAST:event_btCursoActionPerformed

    private void btMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMatriculaActionPerformed
        // TODO add your handling code here:
        String estudiante = (String) jComboBoxEstudiante.getSelectedItem();
        String curso = (String) jComboBoxCurso.getSelectedItem();
        String notaStr = txtNota.getText();

        if (estudiante == null || curso == null || notaStr.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Completa todos los campos de matrícula.");
            return;
        }

        try {
            double nota = Double.parseDouble(notaStr);
            modeloMatricula.addRow(new Object[]{estudiante, curso, nota});
            new PanelMatriculaBD().insertarMatricula(estudiante, curso, nota);
            txtNota.setText("");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "La nota debe ser numérica.");
        }
    }//GEN-LAST:event_btMatriculaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelContenedor;
    private javax.swing.JButton btCurso;
    private javax.swing.JButton btDocente;
    private javax.swing.JButton btEstudiante;
    private javax.swing.JButton btMatricula;
    private javax.swing.JComboBox<String> jComboBoxCurso;
    private javax.swing.JComboBox<String> jComboBoxDocente;
    private javax.swing.JComboBox<String> jComboBoxEstudiante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCursoForm;
    private javax.swing.JMenuItem jMenuDocenteForm;
    private javax.swing.JMenuItem jMenuEstudianteForm;
    private javax.swing.JMenu jMenuFormulario;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenu jMenuListado;
    private javax.swing.JMenuItem jMenuMatriculaForm;
    private javax.swing.JPanel jPanelCurso;
    private javax.swing.JPanel jPanelCursoList;
    private javax.swing.JPanel jPanelDocente;
    private javax.swing.JPanel jPanelDocenteList;
    private javax.swing.JPanel jPanelEstudiante;
    private javax.swing.JPanel jPanelEstudianteList;
    private javax.swing.JPanel jPanelMatricula;
    private javax.swing.JPanel jPanelMatriculaList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField txtCodCurso;
    private javax.swing.JTextField txtCodDocente;
    private javax.swing.JTextField txtCodEstudiante;
    private javax.swing.JTextField txtNomCurso;
    private javax.swing.JTextField txtNomDocente;
    private javax.swing.JTextField txtNomEstudiante;
    private javax.swing.JTextField txtNota;
    // End of variables declaration//GEN-END:variables
}
